version: '3'

services:
  
  frontend:
    
    build: ./my-app
    ports:
      - "3000:3000"
    container_name: frontend
    restart: always
    links:
      - backend


  backend:
    build: ./api
    ports:
      - "8000:8000"
    container_name: backend
    restart: always
    links:
      - db


  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql:latest
    container_name: mysql
    restart: always



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      "8080:80"

